root: true

env:
  browser: true,
  mocha: true

extends:
  - xo-space/esnext

parser: babel-eslint

rules:
  curly:
    - error
    - multi-or-nest
    - consistent
  keyword-spacing:
    - error
    - overrides:
        for:
          after: false
        if:
          after: false
        while:
          after: false
  new-cap:
    - error
    - capIsNew: false
  no-return-assign:
    - error
    - except-parens
  no-unused-expressions:
    - error
    - allowTernary: true
  object-curly-spacing:
    - error
    - always
  quotes:
    - error
    - single
    - avoidEscape: true
  space-before-function-paren:
    - error
    - never
